//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTO.Web.RenwebClassService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", ConfigurationName="RenwebClassService.pw_sch_classSiteSoap")]
    public interface pw_sch_classSiteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_classResponse pw_sch_class(PTO.Web.RenwebClassService.pw_sch_classRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_classResponse> pw_sch_classAsync(PTO.Web.RenwebClassService.pw_sch_classRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_listResponse pw_sch_class_list(PTO.Web.RenwebClassService.pw_sch_class_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_list", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_listResponse> pw_sch_class_listAsync(PTO.Web.RenwebClassService.pw_sch_class_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_progress_catego" +
            "ries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesResponse pw_sch_class_progress_categories(PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_progress_catego" +
            "ries", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesResponse> pw_sch_class_progress_categoriesAsync(PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_progress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_progressResponse pw_sch_class_progress(PTO.Web.RenwebClassService.pw_sch_class_progressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_progress", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_progressResponse> pw_sch_class_progressAsync(PTO.Web.RenwebClassService.pw_sch_class_progressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_calendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_calendarResponse pw_sch_class_calendar(PTO.Web.RenwebClassService.pw_sch_class_calendarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_calendar", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_calendarResponse> pw_sch_class_calendarAsync(PTO.Web.RenwebClassService.pw_sch_class_calendarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_announcement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_announcementResponse pw_sch_class_announcement(PTO.Web.RenwebClassService.pw_sch_class_announcementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_announcement", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_announcementResponse> pw_sch_class_announcementAsync(PTO.Web.RenwebClassService.pw_sch_class_announcementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_homework", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_homeworkResponse pw_sch_class_homework(PTO.Web.RenwebClassService.pw_sch_class_homeworkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_homework", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_homeworkResponse> pw_sch_class_homeworkAsync(PTO.Web.RenwebClassService.pw_sch_class_homeworkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_lessons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_lessonsResponse pw_sch_class_lessons(PTO.Web.RenwebClassService.pw_sch_class_lessonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_lessons", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_lessonsResponse> pw_sch_class_lessonsAsync(PTO.Web.RenwebClassService.pw_sch_class_lessonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_documents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_documentsResponse pw_sch_class_documents(PTO.Web.RenwebClassService.pw_sch_class_documentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_documents", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_documentsResponse> pw_sch_class_documentsAsync(PTO.Web.RenwebClassService.pw_sch_class_documentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_links", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_linksResponse pw_sch_class_links(PTO.Web.RenwebClassService.pw_sch_class_linksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_links", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_linksResponse> pw_sch_class_linksAsync(PTO.Web.RenwebClassService.pw_sch_class_linksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/PW_GetTermList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.PW_GetTermListResponse PW_GetTermList(PTO.Web.RenwebClassService.PW_GetTermListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/PW_GetTermList", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.PW_GetTermListResponse> PW_GetTermListAsync(PTO.Web.RenwebClassService.PW_GetTermListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_syllabus_catego" +
            "ries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesResponse pw_sch_class_syllabus_categories(PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_syllabus_catego" +
            "ries", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesResponse> pw_sch_class_syllabus_categoriesAsync(PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_syllabus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebClassService.pw_sch_class_syllabusResponse pw_sch_class_syllabus(PTO.Web.RenwebClassService.pw_sch_class_syllabusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/classSite/pw_sch_class_syllabus", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_syllabusResponse> pw_sch_class_syllabusAsync(PTO.Web.RenwebClassService.pw_sch_class_syllabusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_classRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public string studentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public int termID;
        
        public pw_sch_classRequest() {
        }
        
        public pw_sch_classRequest(int UserID, string UserType, string SchoolCode, string District, string studentID, string ClassID, int termID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.studentID = studentID;
            this.ClassID = ClassID;
            this.termID = termID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_classResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_classResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_classResult;
        
        public pw_sch_classResponse() {
        }
        
        public pw_sch_classResponse(System.Data.DataSet pw_sch_classResult) {
            this.pw_sch_classResult = pw_sch_classResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_list", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_listRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public int ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public int TermID;
        
        public pw_sch_class_listRequest() {
        }
        
        public pw_sch_class_listRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, int ClassID, int TermID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.TermID = TermID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_listResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_listResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_listResult;
        
        public pw_sch_class_listResponse() {
        }
        
        public pw_sch_class_listResponse(System.Data.DataSet pw_sch_class_listResult) {
            this.pw_sch_class_listResult = pw_sch_class_listResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_progress_categories", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_progress_categoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public int ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public int termID;
        
        public pw_sch_class_progress_categoriesRequest() {
        }
        
        public pw_sch_class_progress_categoriesRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, int ClassID, int termID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.termID = termID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_progress_categoriesResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_progress_categoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_progress_categoriesResult;
        
        public pw_sch_class_progress_categoriesResponse() {
        }
        
        public pw_sch_class_progress_categoriesResponse(System.Data.DataSet pw_sch_class_progress_categoriesResult) {
            this.pw_sch_class_progress_categoriesResult = pw_sch_class_progress_categoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_progress", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_progressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public int ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public string Category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=7)]
        public int termID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=8)]
        public int ID;
        
        public pw_sch_class_progressRequest() {
        }
        
        public pw_sch_class_progressRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, int ClassID, string Category, int termID, int ID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.Category = Category;
            this.termID = termID;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_progressResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_progressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_progressResult;
        
        public pw_sch_class_progressResponse() {
        }
        
        public pw_sch_class_progressResponse(System.Data.DataSet pw_sch_class_progressResult) {
            this.pw_sch_class_progressResult = pw_sch_class_progressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_calendar", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_calendarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        public pw_sch_class_calendarRequest() {
        }
        
        public pw_sch_class_calendarRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_calendarResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_calendarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_calendarResult;
        
        public pw_sch_class_calendarResponse() {
        }
        
        public pw_sch_class_calendarResponse(System.Data.DataSet pw_sch_class_calendarResult) {
            this.pw_sch_class_calendarResult = pw_sch_class_calendarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_announcement", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_announcementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        public pw_sch_class_announcementRequest() {
        }
        
        public pw_sch_class_announcementRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_announcementResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_announcementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_announcementResult;
        
        public pw_sch_class_announcementResponse() {
        }
        
        public pw_sch_class_announcementResponse(System.Data.DataSet pw_sch_class_announcementResult) {
            this.pw_sch_class_announcementResult = pw_sch_class_announcementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_homework", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_homeworkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public string LocalDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=7)]
        public int ShowEvents;
        
        public pw_sch_class_homeworkRequest() {
        }
        
        public pw_sch_class_homeworkRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID, string LocalDate, int ShowEvents) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.LocalDate = LocalDate;
            this.ShowEvents = ShowEvents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_homeworkResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_homeworkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_homeworkResult;
        
        public pw_sch_class_homeworkResponse() {
        }
        
        public pw_sch_class_homeworkResponse(System.Data.DataSet pw_sch_class_homeworkResult) {
            this.pw_sch_class_homeworkResult = pw_sch_class_homeworkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_lessons", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_lessonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public string LocalDate;
        
        public pw_sch_class_lessonsRequest() {
        }
        
        public pw_sch_class_lessonsRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID, string LocalDate) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.LocalDate = LocalDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_lessonsResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_lessonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_lessonsResult;
        
        public pw_sch_class_lessonsResponse() {
        }
        
        public pw_sch_class_lessonsResponse(System.Data.DataSet pw_sch_class_lessonsResult) {
            this.pw_sch_class_lessonsResult = pw_sch_class_lessonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_documents", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_documentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        public pw_sch_class_documentsRequest() {
        }
        
        public pw_sch_class_documentsRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_documentsResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_documentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_documentsResult;
        
        public pw_sch_class_documentsResponse() {
        }
        
        public pw_sch_class_documentsResponse(System.Data.DataSet pw_sch_class_documentsResult) {
            this.pw_sch_class_documentsResult = pw_sch_class_documentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_links", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_linksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public string ClassID;
        
        public pw_sch_class_linksRequest() {
        }
        
        public pw_sch_class_linksRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, string ClassID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_linksResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_linksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_linksResult;
        
        public pw_sch_class_linksResponse() {
        }
        
        public pw_sch_class_linksResponse(System.Data.DataSet pw_sch_class_linksResult) {
            this.pw_sch_class_linksResult = pw_sch_class_linksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PW_GetTermList", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class PW_GetTermListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public int StudentID;
        
        public PW_GetTermListRequest() {
        }
        
        public PW_GetTermListRequest(string District, int StudentID) {
            this.District = District;
            this.StudentID = StudentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PW_GetTermListResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class PW_GetTermListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet PW_GetTermListResult;
        
        public PW_GetTermListResponse() {
        }
        
        public PW_GetTermListResponse(System.Data.DataSet PW_GetTermListResult) {
            this.PW_GetTermListResult = PW_GetTermListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_syllabus_categories", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_syllabus_categoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public int ClassID;
        
        public pw_sch_class_syllabus_categoriesRequest() {
        }
        
        public pw_sch_class_syllabus_categoriesRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, int ClassID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_syllabus_categoriesResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_syllabus_categoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_syllabus_categoriesResult;
        
        public pw_sch_class_syllabus_categoriesResponse() {
        }
        
        public pw_sch_class_syllabus_categoriesResponse(System.Data.DataSet pw_sch_class_syllabus_categoriesResult) {
            this.pw_sch_class_syllabus_categoriesResult = pw_sch_class_syllabus_categoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_syllabus", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_syllabusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=4)]
        public int StudentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=5)]
        public int ClassID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=6)]
        public int SyllabusID;
        
        public pw_sch_class_syllabusRequest() {
        }
        
        public pw_sch_class_syllabusRequest(int UserID, string UserType, string SchoolCode, string District, int StudentID, int ClassID, int SyllabusID) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.StudentID = StudentID;
            this.ClassID = ClassID;
            this.SyllabusID = SyllabusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_class_syllabusResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/classSite/", IsWrapped=true)]
    public partial class pw_sch_class_syllabusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/classSite/", Order=0)]
        public System.Data.DataSet pw_sch_class_syllabusResult;
        
        public pw_sch_class_syllabusResponse() {
        }
        
        public pw_sch_class_syllabusResponse(System.Data.DataSet pw_sch_class_syllabusResult) {
            this.pw_sch_class_syllabusResult = pw_sch_class_syllabusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pw_sch_classSiteSoapChannel : PTO.Web.RenwebClassService.pw_sch_classSiteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pw_sch_classSiteSoapClient : System.ServiceModel.ClientBase<PTO.Web.RenwebClassService.pw_sch_classSiteSoap>, PTO.Web.RenwebClassService.pw_sch_classSiteSoap {
        
        public pw_sch_classSiteSoapClient() {
        }
        
        public pw_sch_classSiteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pw_sch_classSiteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pw_sch_classSiteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pw_sch_classSiteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PTO.Web.RenwebClassService.pw_sch_classResponse pw_sch_class(PTO.Web.RenwebClassService.pw_sch_classRequest request) {
            return base.Channel.pw_sch_class(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_classResponse> pw_sch_classAsync(PTO.Web.RenwebClassService.pw_sch_classRequest request) {
            return base.Channel.pw_sch_classAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_listResponse pw_sch_class_list(PTO.Web.RenwebClassService.pw_sch_class_listRequest request) {
            return base.Channel.pw_sch_class_list(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_listResponse> pw_sch_class_listAsync(PTO.Web.RenwebClassService.pw_sch_class_listRequest request) {
            return base.Channel.pw_sch_class_listAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesResponse pw_sch_class_progress_categories(PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesRequest request) {
            return base.Channel.pw_sch_class_progress_categories(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesResponse> pw_sch_class_progress_categoriesAsync(PTO.Web.RenwebClassService.pw_sch_class_progress_categoriesRequest request) {
            return base.Channel.pw_sch_class_progress_categoriesAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_progressResponse pw_sch_class_progress(PTO.Web.RenwebClassService.pw_sch_class_progressRequest request) {
            return base.Channel.pw_sch_class_progress(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_progressResponse> pw_sch_class_progressAsync(PTO.Web.RenwebClassService.pw_sch_class_progressRequest request) {
            return base.Channel.pw_sch_class_progressAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_calendarResponse pw_sch_class_calendar(PTO.Web.RenwebClassService.pw_sch_class_calendarRequest request) {
            return base.Channel.pw_sch_class_calendar(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_calendarResponse> pw_sch_class_calendarAsync(PTO.Web.RenwebClassService.pw_sch_class_calendarRequest request) {
            return base.Channel.pw_sch_class_calendarAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_announcementResponse pw_sch_class_announcement(PTO.Web.RenwebClassService.pw_sch_class_announcementRequest request) {
            return base.Channel.pw_sch_class_announcement(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_announcementResponse> pw_sch_class_announcementAsync(PTO.Web.RenwebClassService.pw_sch_class_announcementRequest request) {
            return base.Channel.pw_sch_class_announcementAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_homeworkResponse pw_sch_class_homework(PTO.Web.RenwebClassService.pw_sch_class_homeworkRequest request) {
            return base.Channel.pw_sch_class_homework(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_homeworkResponse> pw_sch_class_homeworkAsync(PTO.Web.RenwebClassService.pw_sch_class_homeworkRequest request) {
            return base.Channel.pw_sch_class_homeworkAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_lessonsResponse pw_sch_class_lessons(PTO.Web.RenwebClassService.pw_sch_class_lessonsRequest request) {
            return base.Channel.pw_sch_class_lessons(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_lessonsResponse> pw_sch_class_lessonsAsync(PTO.Web.RenwebClassService.pw_sch_class_lessonsRequest request) {
            return base.Channel.pw_sch_class_lessonsAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_documentsResponse pw_sch_class_documents(PTO.Web.RenwebClassService.pw_sch_class_documentsRequest request) {
            return base.Channel.pw_sch_class_documents(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_documentsResponse> pw_sch_class_documentsAsync(PTO.Web.RenwebClassService.pw_sch_class_documentsRequest request) {
            return base.Channel.pw_sch_class_documentsAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_linksResponse pw_sch_class_links(PTO.Web.RenwebClassService.pw_sch_class_linksRequest request) {
            return base.Channel.pw_sch_class_links(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_linksResponse> pw_sch_class_linksAsync(PTO.Web.RenwebClassService.pw_sch_class_linksRequest request) {
            return base.Channel.pw_sch_class_linksAsync(request);
        }
        
        public PTO.Web.RenwebClassService.PW_GetTermListResponse PW_GetTermList(PTO.Web.RenwebClassService.PW_GetTermListRequest request) {
            return base.Channel.PW_GetTermList(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.PW_GetTermListResponse> PW_GetTermListAsync(PTO.Web.RenwebClassService.PW_GetTermListRequest request) {
            return base.Channel.PW_GetTermListAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesResponse pw_sch_class_syllabus_categories(PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesRequest request) {
            return base.Channel.pw_sch_class_syllabus_categories(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesResponse> pw_sch_class_syllabus_categoriesAsync(PTO.Web.RenwebClassService.pw_sch_class_syllabus_categoriesRequest request) {
            return base.Channel.pw_sch_class_syllabus_categoriesAsync(request);
        }
        
        public PTO.Web.RenwebClassService.pw_sch_class_syllabusResponse pw_sch_class_syllabus(PTO.Web.RenwebClassService.pw_sch_class_syllabusRequest request) {
            return base.Channel.pw_sch_class_syllabus(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebClassService.pw_sch_class_syllabusResponse> pw_sch_class_syllabusAsync(PTO.Web.RenwebClassService.pw_sch_class_syllabusRequest request) {
            return base.Channel.pw_sch_class_syllabusAsync(request);
        }
    }
}
