//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTO.Web.RenwebDirectoryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", ConfigurationName="RenwebDirectoryService.pw_sch_directorySoap")]
    public interface pw_sch_directorySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_familyResponse pw_sch_directory_family(PTO.Web.RenwebDirectoryService.pw_sch_directory_familyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_familyResponse> pw_sch_directory_familyAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_familyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_prin" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printResponse pw_sch_directory_family_print(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_prin" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printResponse> pw_sch_directory_family_printAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_school", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolResponse pw_sch_directory_school(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_school", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolResponse> pw_sch_directory_schoolAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_memb" +
            "ers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersResponse pw_sch_directory_family_members(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_memb" +
            "ers", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersResponse> pw_sch_directory_family_membersAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_grad" +
            "elevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelResponse pw_sch_directory_family_gradelevel(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_family_grad" +
            "elevel", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelResponse> pw_sch_directory_family_gradelevelAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_schoolinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoResponse pw_sch_directory_schoolinfo(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.renweb.com/webservices/pwSchool/directory/pw_sch_directory_schoolinfo", ReplyAction="*")]
        System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoResponse> pw_sch_directory_schoolinfoAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_familyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=4)]
        public string FilterName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=5)]
        public string DirectoryType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=6)]
        public string Criteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=7)]
        public string classCriteria;
        
        public pw_sch_directory_familyRequest() {
        }
        
        public pw_sch_directory_familyRequest(int UserID, string UserType, string SchoolCode, string District, string FilterName, string DirectoryType, string Criteria, string classCriteria) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.FilterName = FilterName;
            this.DirectoryType = DirectoryType;
            this.Criteria = Criteria;
            this.classCriteria = classCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_familyResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_familyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_familyResult;
        
        public pw_sch_directory_familyResponse() {
        }
        
        public pw_sch_directory_familyResponse(System.Data.DataSet pw_sch_directory_familyResult) {
            this.pw_sch_directory_familyResult = pw_sch_directory_familyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_print", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_printRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=4)]
        public string FilterName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=5)]
        public string DirectoryType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=6)]
        public string Criteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=7)]
        public string classCriteria;
        
        public pw_sch_directory_family_printRequest() {
        }
        
        public pw_sch_directory_family_printRequest(int UserID, string UserType, string SchoolCode, string District, string FilterName, string DirectoryType, string Criteria, string classCriteria) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.FilterName = FilterName;
            this.DirectoryType = DirectoryType;
            this.Criteria = Criteria;
            this.classCriteria = classCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_printResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_printResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_family_printResult;
        
        public pw_sch_directory_family_printResponse() {
        }
        
        public pw_sch_directory_family_printResponse(System.Data.DataSet pw_sch_directory_family_printResult) {
            this.pw_sch_directory_family_printResult = pw_sch_directory_family_printResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_school", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_schoolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=4)]
        public string FilterName;
        
        public pw_sch_directory_schoolRequest() {
        }
        
        public pw_sch_directory_schoolRequest(int UserID, string UserType, string SchoolCode, string District, string FilterName) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.FilterName = FilterName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_schoolResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_schoolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_schoolResult;
        
        public pw_sch_directory_schoolResponse() {
        }
        
        public pw_sch_directory_schoolResponse(System.Data.DataSet pw_sch_directory_schoolResult) {
            this.pw_sch_directory_schoolResult = pw_sch_directory_schoolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_members", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_membersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=4)]
        public int Person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=5)]
        public int Address;
        
        public pw_sch_directory_family_membersRequest() {
        }
        
        public pw_sch_directory_family_membersRequest(int UserID, string UserType, string SchoolCode, string District, int Person, int Address) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
            this.Person = Person;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_membersResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_membersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_family_membersResult;
        
        public pw_sch_directory_family_membersResponse() {
        }
        
        public pw_sch_directory_family_membersResponse(System.Data.DataSet pw_sch_directory_family_membersResult) {
            this.pw_sch_directory_family_membersResult = pw_sch_directory_family_membersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_gradelevel", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_gradelevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        public pw_sch_directory_family_gradelevelRequest() {
        }
        
        public pw_sch_directory_family_gradelevelRequest(int UserID, string UserType, string SchoolCode, string District) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_family_gradelevelResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_family_gradelevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_family_gradelevelResult;
        
        public pw_sch_directory_family_gradelevelResponse() {
        }
        
        public pw_sch_directory_family_gradelevelResponse(System.Data.DataSet pw_sch_directory_family_gradelevelResult) {
            this.pw_sch_directory_family_gradelevelResult = pw_sch_directory_family_gradelevelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_schoolinfo", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_schoolinfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=1)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=2)]
        public string SchoolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=3)]
        public string District;
        
        public pw_sch_directory_schoolinfoRequest() {
        }
        
        public pw_sch_directory_schoolinfoRequest(int UserID, string UserType, string SchoolCode, string District) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.SchoolCode = SchoolCode;
            this.District = District;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pw_sch_directory_schoolinfoResponse", WrapperNamespace="http://www.renweb.com/webservices/pwSchool/directory/", IsWrapped=true)]
    public partial class pw_sch_directory_schoolinfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.renweb.com/webservices/pwSchool/directory/", Order=0)]
        public System.Data.DataSet pw_sch_directory_schoolinfoResult;
        
        public pw_sch_directory_schoolinfoResponse() {
        }
        
        public pw_sch_directory_schoolinfoResponse(System.Data.DataSet pw_sch_directory_schoolinfoResult) {
            this.pw_sch_directory_schoolinfoResult = pw_sch_directory_schoolinfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pw_sch_directorySoapChannel : PTO.Web.RenwebDirectoryService.pw_sch_directorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pw_sch_directorySoapClient : System.ServiceModel.ClientBase<PTO.Web.RenwebDirectoryService.pw_sch_directorySoap>, PTO.Web.RenwebDirectoryService.pw_sch_directorySoap {
        
        public pw_sch_directorySoapClient() {
        }
        
        public pw_sch_directorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pw_sch_directorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pw_sch_directorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pw_sch_directorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_familyResponse pw_sch_directory_family(PTO.Web.RenwebDirectoryService.pw_sch_directory_familyRequest request) {
            return base.Channel.pw_sch_directory_family(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_familyResponse> pw_sch_directory_familyAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_familyRequest request) {
            return base.Channel.pw_sch_directory_familyAsync(request);
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printResponse pw_sch_directory_family_print(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printRequest request) {
            return base.Channel.pw_sch_directory_family_print(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printResponse> pw_sch_directory_family_printAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_printRequest request) {
            return base.Channel.pw_sch_directory_family_printAsync(request);
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolResponse pw_sch_directory_school(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolRequest request) {
            return base.Channel.pw_sch_directory_school(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolResponse> pw_sch_directory_schoolAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolRequest request) {
            return base.Channel.pw_sch_directory_schoolAsync(request);
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersResponse pw_sch_directory_family_members(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersRequest request) {
            return base.Channel.pw_sch_directory_family_members(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersResponse> pw_sch_directory_family_membersAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_membersRequest request) {
            return base.Channel.pw_sch_directory_family_membersAsync(request);
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelResponse pw_sch_directory_family_gradelevel(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelRequest request) {
            return base.Channel.pw_sch_directory_family_gradelevel(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelResponse> pw_sch_directory_family_gradelevelAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_family_gradelevelRequest request) {
            return base.Channel.pw_sch_directory_family_gradelevelAsync(request);
        }
        
        public PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoResponse pw_sch_directory_schoolinfo(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoRequest request) {
            return base.Channel.pw_sch_directory_schoolinfo(request);
        }
        
        public System.Threading.Tasks.Task<PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoResponse> pw_sch_directory_schoolinfoAsync(PTO.Web.RenwebDirectoryService.pw_sch_directory_schoolinfoRequest request) {
            return base.Channel.pw_sch_directory_schoolinfoAsync(request);
        }
    }
}
